package de.unikassel.se.dpss20;

// Use this class to start the app from your IDE
// DO NOT edit this file, put your changes in the Main class.
public class Launcher
{
	public static void main(String[] args)
	{
		Main.main(args);
	}
}
